name: bakta
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - trnascan-se=2.0.6
  - aragorn=1.2.38
  - infernal=1.1.3
  - piler-cr
  - prodigal=2.6.3
  - diamond=2.0.4
  - blast>=2.7.1
